# .github/workflows/ci-cd.yml

name: CI/CD Pipeline for OrientAI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build, Test and Push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: |
          frontend/package-lock.json
          backend/package-lock.json

    - name: Install Frontend Dependencies
      run: npm ci
      working-directory: ./frontend

    - name: Build Frontend
      run: npm run build
      working-directory: ./frontend

    - name: Install Backend Dependencies
      run: npm ci
      working-directory: ./backend

    - name: Test Frontend
      run: npm test
      working-directory: ./frontend
    #
    # - name: Test Backend
    #   run: npm test
    #   working-directory: ./backend

    - name: Log in to Docker Hub
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Backend Docker image
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: true
        tags: YOUR_DOCKERHUB_USERNAME/orientai-backend:latest, YOUR_DOCKERHUB_USERNAME/orientai-backend:${{ github.sha }}

  deploy:
    name: Deploy to Kubernetes
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config
        chmod 600 $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: |
        # Apply configurations that do not change frequently
        kubectl apply -f mysql-init-configmap.yaml
        kubectl apply -f mysql-secret.yaml
        kubectl apply -f mysql-deployment.yaml
        kubectl apply -f mysql-service.yaml
        kubectl apply -f ollama-deployment.yaml
        kubectl apply -f ollama-service.yaml
        kubectl apply -f backend-service.yaml

        # Update the backend deployment with the new image
        # Make sure the deployment and container names are correct
        kubectl set image deployment/backend backend=YOUR_DOCKERHUB_USERNAME/orientai-backend:${{ github.sha }}
